### PR TITLE
I propose its version of isTypedArray

### PR DESCRIPTION
**Pull request by xguest**
Excuse me, I earned money.

I simplified the code.
It performs fewer operations.
All your tests pass.
One commit one change.
The files have a comment.

P.S. Now I'm out of work decided to recall Javascript, do not mind that your repository?

### CODE REVIEW

**Comment by xguest** [comment]
Sorry, held locally.
Now I corrected.

**Comment by xguest** [comment]
Error in RegExp the last  commit, fix tomorrow, you can read the rest

**Comment by ljharb** [comment]
- This module has been manually tested in every single version of node, io.js, Firefox, Chrome, IE, Opera, Safari, Edge, and iOS Safari. In which browsers have you tested your changes?
 - To what benefit is "fewer operations"? The number of operations of a piece of code are entirely irrelevant to the performance of the code, but if there's too *few* operations, it can greatly harm readability of the code.

**Comment by xguest** [comment]
Hi @ljharb!
I'm sorry I did not mean to offend you or your work.
I only recall JavaScript.
Once again, I lost my job and sometimes get teleworking over the internet. Therefore, more time, decided to recall the JavaScript, chose to study your repository - what to ask before.

Now, in fact.
- To test my code is not necessary, I added this command only RegExp.test
It used since the nineties.
- The words "less operation", I meant less work or action, logic operations.

For example in the commit:
[Optimize the variable declaration](https://github.com/ljharb/is-typed-array/pull/14/commits/2d49ff8087619bf362a73378f68b56c5c0af44bc)

I did not change the logic of the program, only I changed the order of the variable declaration.
For example:
Why check compiler support teams on every call?
I ordered this test to the export function.

Or why use a loop where you can do without it?
Or why create an object for processing lines, if there is a built in function, and it is by definition more quickly.

- As for readability, getting lost in the forest easier than wood and easier to read three lines or book?

If interested read the comments in the files, ready to answer all questions.

P.S. I Friendship suggest you, you take it?

**Comment by xguest** [comment]
Help me.
My 'node js v5.12.0' set by 'nvm 1.1.1' windows in all the tests pass, and Travis CI produces errors.

**Comment by xguest** [comment]
Does not work in --es-staging mode tomorrow will look at us now night.

**Comment by ljharb** [comment]
@xguest `RegExp#exec` definitely still needs to be tested, as it both has many variations across browsers, and also Typed Arrays themselves have many variations across browsers.

**Comment by xguest** [comment]
Hello!
I Found an error, fixed, being tested.

I have a question for you, do you mean that if the compiler supports Symbol's, all objects TypedArray duty to maintain Symbol.toStringTag it really so?

P.S. My opinion: it is an indirect dependency.

**Comment by xguest** [comment]
How to test this module in each version of Firefox, Chrome, IE, Opera, Safari, Edge, and the operating system IOS Safari.
Do you know any online service?

**Comment by ljharb** [comment]
JS has no compiler - and yes, if the engine supports `Symbol.toStringTag`, then that means `Object.prototype.toString` is no longer reliable. The thing that matters here is 100% robust unforgeable certainty about if something is a typed array or not - there must not exist any value that is not a typed array that passes this check.

I usually use browserstack to test.

**Comment by xguest** [comment]
Thank you.
A long time ago we were taught that any programming language is the interpreter and compiler, but you know better corrected, 'engine' - probably interpreter commands.
Tomorrow I will try "browserstack"

P.S. I added Object.prototype.toString
if engine support Symbol and Symbol.toStringTag not found in object, is that correct?

**Comment by ljharb** [comment]
Yes, that's true, it is only not reliable when there's a `Symbol.toStringTag` present - however, the spec requires that all the builtins have it present by default, so there's not really any benefit in doing that runtime check on each instance passed in.

**Comment by xguest** [comment]
Now I do not remember on what type of object was a Symbol, and Symbol.toStringTag return undefined.
Thank.

**Comment by xguest** [comment]
www.browserstack.com server charge, but as you know this is not for me. 
I found www.browserscope.org service. 
But now I have no time. 
If you want I can rewrite the test over the keys of the object, or something else.

**Comment by ljharb** [comment]
While I appreciate your contributions (and any contributions), I don't think there is any inherent value in "fewer operations" - and I think correctness and readability is far more important than efficiency and performance, in every case, in every language.

I think a more successful approach might be making multiple small iterative PRs - in other words, very small and focused changes, with well-explained rationale, benchmarks, and testing results - rather than a large, sweeping change with no benefit to the project maintainer.

**Comment by xguest** [comment]
I'm sorry that I ruined your time.
Thank you.

**Comment by ljharb** [comment]
@xguest not at all, i appreciate the effort! It's just that a massive rewrite of any project is often both well-intentioned, but poorly-received, as well as risky to accept.

**Comment by xguest** [comment]
I'm understood, thank you.
I would like to be useful, otherwise you are not interested to talk to me, and I will not be able to learn something.

You do not even fit the first sentence, [Optimize the variable declaration](https://github.com/ljharb/is-typed-array/pull/14/commits/e9834f1d3f4c6363f2b657e386e4f9bdfeb8e5d4)?

**Comment by ljharb** [comment]
If you mean, replacing the use of `forEach` with `every` or `some`, that's a great point and a great optimization! I'd be happy to accept a PR that uses something like https://www.npmjs.com/package/array-every instead of `for-each`. I'm not a huge fan of that specific package, and no better one seems to exist yet, but that is definitely the kind of targeted optimization that I recommend you make in its own PR :-)

**Pull request closed without merging**
